sudo: required

language: generic

services:
  - docker

before_install:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t sergkh/nginx-autoproxy .

script:
  - docker run --name proxy -d -p 9453:80 sergkh/nginx-autoproxy; sleep 20
  - curl --retry 10 --retry-delay 5 -v http://localhost:9453
  - docker logs proxy
    
after_success:  
  - docker tag sergkh/nginx-autoproxy:0.2 
  - docker tag sergkh/nginx-autoproxy:latest     
  - docker push sergkh/nginx-autoproxy:late