[template]
src = "default.conf.tmpl"
dest = "/etc/nginx/conf.d/default.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/services"
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/service nginx reload"